# ChaldOS — systemd-boot entry
title   🔵 ChaldOS Gaming Edition v2.0
linux   /%INSTALL_DIR%/boot/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisodevice=UUID=${ARCHISO_UUID} quiet splash
